agent: 'iql'
debug: False

n_rnn_hidden: 16
n_rnn_layers: 1
rnn_directions: 1
bidirectional: False

# parameters for RL discounting strategies
return_type: 'average'   # discount | average; is average gamma and lamda -> 1.
gamma: 0.99
lambda_: 0.95

# parameters for the RL rollout
normalize_reward: True  # reward received is normalised
shuffle_rollout: True  # rollout trajectory data is shuffled
replay_buffer_size: 65536 #FIXME remove random sampling
replay_buffer_step: 8192
preserve_trajectories : False

# train
n_step: 8192
max_epi_length: 2880
n_training_workers: 16
total_interactions: 5000000 # total number of interactions the agent will train for #800000
n_interactions_lr_decay: 4000000

batch_size : 8192
n_pi_epochs: 100

# test
n_testing_workers: 5
max_test_epi_len: 288  # testing conducted for 1 day: 12 steps/hr * 24 hours

# validation
n_val_trials: 5 #500

#data source
data_preload: true,
data_type: "simulated" #simulated | clinical
data_protocols: ["evaluation","training"] #None defaults to all
data_algorithms : ["G2P2C","AUXML", "PPO","TD3"] #None defaults to all
use_all_interactions : false

n_hidden: 16
noise_model: "normal_dist"
noise_std: 0.05
noise_application: 0
target_action_std: 0.05
target_action_lim: 0.2
soft_tau: 0.005

beta : 2.5

pi_lr: 1e-5
vf_lr: 0.001
cr_lr: 1e-3


n_handcrafted_features: -10 #FIXME
n_features: 32
use_handcraft: 0
